### ISSUE TITLE
definition of grapheme

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#10]
http://www.w3.org/TR/2015/WD-charmod-norm-20150721/#def-grapheme-cluster

[1]
"A grapheme is a sequence of one or more Unicode characters that form a single user-perceived "character"."

how about: 

"A grapheme is a sequence of one or more Unicode characters in visually rendered text that a typical user would perceive as being a single unit in the writing system."

[2]
"grapheme cluster, which roughly corresponds to the user's perception of where the character boundaries occur in a visually rendered text"

how about:

"grapheme cluster, which is an approximation to sequences it is expected that a user would perceive as graphemes"

[3]
we should mention that we assume the extended grapheme clusters

**Comment by aphillips** [comment]
For [1] I adopted the change, omitting the "in visually rendered text". While a grapheme is a visual unit, I think it clutters the definition: a grapheme is still a grapheme, even when you can't see it ;-)

For [2], annoyingly charmod-fun doesn't provide a formal definition, although it uses the term. It's semi-defined in a note following C012. UAX29 also doesn't bother to formally define the term.

For [3], I agree. The result is that I rewrote this paragraph. I also added an example block that may need more work (or might be removed).

**Comment by aphillips** [comment]
Fixed in https://github.com/w3c/charmod-norm/commit/e4edc2390f4fcbdead7b63b2736b0f32c7c32b98
