### ISSUE TITLE
Make coeng homonyms look better

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#111]
2.2.4 Limitations of Normalization
http://w3c.github.io/charmod-norm/#normalizationLimitations

> the character sequences U+17D2 U+178F (្ស) and U+17D2 U+178A (្ដ) in Khmer

Showing these sequences as characters in the parens is not very helpful since (a) they lack something to combine with and get tangled with the parens, and (b) the similarity is not necessarily clear in such a context using default fonts.  I suggest using a hyphen or a Khmer consonant as the first item in the sequence, eg. 

-្ត -្ដ

or 

ក្ត ក្ដ

**Comment by r12a** [comment]
Actually, it would also be helpful to add the Unicode name for

> Some examples of this include U+08A1 ࢡ,

since people are unlikely to be able to see the glyph. (And might be useful to add for the khmer and other characters too.)

**Comment by aphillips** [comment]
Fixed in above commit.
