### ISSUE TITLE
Formatting, not control characters

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#112]
2.4 Unicode Controls and Invisible Markers
http://w3c.github.io/charmod-norm/#unicodeControls

The title and text in this section (and elsewhere) should not call formatting characters 'control characters'.  They are different things in the Unicode glossary.

**Comment by aphillips** [comment]
Fixed as:

      <section id="invisibleCharacters">
        <h3>Invisible Unicode Characters That Affect Matching</h3>
