### ISSUE TITLE
Definition of vocabulary: enumerated values

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#12]
http://www.w3.org/TR/2015/WD-charmod-norm-20150721/#dfn_vocabulary

"For example, HTML defines the names of its elements and attributes, which defines the "vocabulary" of HTML markup."

suggest -->

"For example, HTML defines the names of its elements and attributes, as well as enumerated attribute values, which defines the "vocabulary" of HTML markup."

**Comment by aphillips** [comment]
Fixed in https://github.com/w3c/charmod-norm/commit/e4edc2390f4fcbdead7b63b2736b0f32c7c32b98
