### ISSUE TITLE
Terminology examples fonts

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#121]
1.4.1 Terminology Examples
https://w3c.github.io/charmod-norm/#terminology-examples

> Syntactic content is shown in a monospaced font.

The font shown on an ipad isn't monospaced.

Also "William Shakespeare" alt text is monospaced (on desktop), but that isn't syntactic content afaia.

Why not replace that panel with an image, and use some other conventions (double underlines or wavy underlines?) rather than monospacing (since the monospacing is not that easily distinguished in some cases anyway).  Perhaps serif vs non-serif would work, given a font choice that shows the difference clearly?

**Comment by asmusf** [comment]
I think the convention was intended to avoid relying on color distinction alone. However, there are ways to address that.

First, everything inside <> is syntax - EXCEPT for some of the attribute values (some of the values in "")
So, use a color for the syntax (no underline), and another color for non-translatable values like "en" and "Utf-8". Explain that meta-convention, then use tooltips on all attribute values to give their status. (Perhaps also tool tips for syntax values).

Continue to use italics/bold/background for "user values" and natural language text (but also tool tips).

The explanation of "user values" could be streamlined. "unreserved syntactic content" is not something that engenders easy understanding :(

**Comment by aphillips** [comment]
We avoid using color alone for accessibility reasons (color blindness). We need to have two variations when using color (hence red-underlined and blue-with-gray-background).

The font defintion in the stylesheet is pretty monospaced:

> 	font-family: Consolas, "Andale Mono", "Lucida Console", "Lucida Sans Typewriter", Monaco, "Courier New", NoToFu, monospace; 

The only font in there that isn't actually a monospaced font is "NoToFu", which is our fallback face for missing glyphs and doesn't draw here. Are you sure the text doesn't just look prettier while being in a mono font on iPad?

I am open to suggestions, but this is a difficult example to build by itself. I could, as you suggest, make a graphic just to be sure everyone gets the picture---as it were ;-).

**Comment by asmusf** [comment]
On 10/25/2017 9:27 PM, Addison Phillips wrote:
>
> We avoid using color alone for accessibility reasons (color 
> blindness). We need to have two variations when using color (hence 
> red-underlined and blue-with-gray-background).
>
My suggestion was to explain some stuff in terms of where the text 
occurs (inside <>, outside "" etc.) so that some of the color/format 
distinctions become non-essential; if that is done, they can be made 
subtle but redundant. A color blind reader will not be lost, and all 
readers won't have to struggle with so much distraction (like all those 
underlines).

I think the element names would work for that, like syntax characters 
they could stay unmarked. Then you only need to distinguish 
reserved/user-defined attribute identifiers from full text.

**Comment by bert-github** [comment]
The reason it is not monospaced is that there is a typo in the style sheet: "monospaced" should be "monospace".

**Comment by aphillips** [comment]
@bert-github Good catch. It's a different style than the ones I was looking at, but you're correct.

**Comment by r12a** [comment]
Well it's better, but can i suggest we use a serif font for nat lang and user values?  On my system you still have to squint  a little to see that Shakespeare isn't monospaced, and that William Shakespeare is italicised.

**Comment by aphillips** [comment]
Hmm... I could try that. Are we chasing our tails though? Our accessibility colleagues would have a field day pointing out how this example isn't any more legible to the vision impaired. Maybe I should show the "file" and then show separate examples of each type?
