### ISSUE TITLE
Better exampling for case folding section

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#122]
Case folding
https://w3c.github.io/charmod-norm/#dfn-case-folding

You have to go through long stretches of abstract explanations before coming to examples. I'd prefer to include more examples, scattered throughout the paragraphs.  Ie, have an example right after introducing common case foldings. Then another after introducing full.  That way readers can latch onto an example to clarify and remind themselves what the concepts represent as they read.

**Comment by aphillips** [comment]
Care to suggest some?

**Comment by aphillips** [comment]
@r12a: Check the above PR and see what you think.

**Comment by r12a** [comment]
Much better!
