### ISSUE TITLE
Example 4 table

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#123]
2.1 Case Folding
https://w3c.github.io/charmod-norm/#definitionCaseFolding
Example 4

The alignments of the cells fails on an ipad. 

Actually, i think the table would be clearer if it was flipped so that Source, Full, etc was down the side, and the actual examples were followed (to the right) by code point values and names.

eg. 

Source      ᾛ          U+1F9B  [GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI]
Full           ἣι          U+1F23 [GREEK SMALL LETTER ETA WITH DASIA AND VARIA] + U+03B9 [GREEK SMALL LETTER IOTA]
Simple     ....

**Comment by asmusf** [comment]
Agree

**Comment by aphillips** [comment]
Fixed. In order to make it make sense, I rewrote the introducing text slightly.

**Comment by r12a** [comment]
Much clearer. Thanks.
