### ISSUE TITLE
Why see charmod 4.6?

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#128]
2.4 Character Escapes
https://w3c.github.io/charmod-norm/#characterEscapes

> See also, Section 4.6 of [CHARMOD].

I find myself asking why i should see that. Do i have to follow the link because this section is missing something? 

I think it would be helpful to briefly say why one should follow the link.

**Comment by aphillips** [comment]
That section has a bunch of text about character escapes? [Elsewhere](http://w3c.github.io/charmod-norm/#expandingCharacterEscapes) in charmod-norm we say:

> This is discussed in detail in Section 4.6 of [CHARMOD] as well as above.

I converted the text to a note and added explanation.

**Comment by r12a** [comment]
Thanks. However, it occurs to me that one more edit would be useful. Can we make the text "Section 4.6" link directly to section 4.6 of Charmod - rather forcing the user to chase around the trees in order to get there from the [CHARMOD] link.  (We can keep the latter – i'm asking for an additional link.)

**Comment by r12a** [comment]
Still waiting for an answer to the link question. Otherwise ready to close.

**Comment by aphillips** [comment]
Added a direct link to section 4.6
