### ISSUE TITLE
Show ES6 escapes

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#129]
2.4 Character Escapes
https://w3c.github.io/charmod-norm/#characterEscapes

> In a JavaScript or JSON file, it can appear as \u20ac while in a CSS stylesheet it can appear as \20ac.

->
In a JavaScript or JSON file, it can appear as \u{20AC} or \u20ac while in a CSS stylesheet it can appear as \20ac.

I suggest this as i think it will date charmod-norm less, and because it showcases a format that is particularly useful for i18n discussions, because it shows that supp chars don't have to be represented any more using utf-16 code units.

It may be good to check the rest of the document for js escapes.

**Comment by aphillips** [comment]
Made the change and checked for other instances of \u (there were none)
