### ISSUE TITLE
Is 'syntactic content' a better term than 'markup'?

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#13]
while cross-referencing with Charmod Fundamentals, i noticed that they refer to syntax and syntactic elements.  It seemed to me that 'syntactic content' (cf. 'natural language content') might be clearer than 'markup' for our purposes.  There'd be less overloading.

**Comment by aphillips** [comment]
That's a good point, although I'd eschew the baroque sounding "syntactic content" in favor of just 'syntax' or, in the specific case, 'syntactic element'--so that it reads like charmod-fun. Perhaps change this:

> _Markup_ is any text in a document format or protocol that belongs to 
> the structure of the format or protocol.

To read:

> _Syntax_ or _syntactic elements_ are the text in a document format or protocol
>  that belongs to the structure of the format or protocol.

**Comment by duerst** [comment]
I agree. "Markup is any text in a document format or protocol that belongs to
the structure of the format or protocol." sounds okay for formats like HTML, but not for protocols.

**Comment by r12a** [comment]
i thought about using 'syntax' or 'syntactic elements', before suggesting 'syntactic content', and thought that 'syntactic content' was better.

'syntax' is for me a bit too general a word, whose dictionary definition relates to more than we need.

'syntactic elements' seemed too vague, and when used in charmod-fun (once only) i think that 'elements' is just a general word, rather than part of a technical term.

'syntactic content' is an unusual pairing which makes it more recognisable and specific for what we need, with less chance for confusion, but in particular it contrasts with and nicely complements 'natural language content', which is the term we use for the rest of the stuff in a resource.

**Comment by klensin** [comment]
When talking about compilers and related formal languages, people quite often talk (or used to) about "lexical content" or variations, thereby avoiding some of the issues with other meanings and connotations of "syntax".   Don't know if that would be helpful here or not.

**Comment by aphillips** [comment]
I did a search of uses of the word 'markup' in the current document and agree that 'syntactic content' can work and doesn't seem abnormal. Any objections to making the change?

**Comment by klensin** [comment]
Wfm

**Comment by r12a** [comment]
fixed by https://github.com/w3c/charmod-norm/commit/41948a4a7eaa5f6c1b33956c5f51bfac47483091
