### ISSUE TITLE
Example 7 shouldn't be in a panel

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#130]
2.5 Invisible Unicode Characters
https://w3c.github.io/charmod-norm/#invisibleCharacters
Example 7

This example immediately follows another example about indic scripts, so the yellow panel seems odd.  

In fact, imo, this shouldn't have a yellow panel anyway, since it's making a counter-point, ie. that ZWNJ isn't always transparent to the meaning, and i think the paragraph should start out by saying that.

**Comment by aphillips** [comment]
Fixed.
