### ISSUE TITLE
Other Types of Equivalence are other types of equivalence

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#139]
2.8 Other Types of Equivalence
https://w3c.github.io/charmod-norm/#otherEquivalences

It seems to me that this section belongs in the other document, rather than in the string matching one. No one is going to want to be concerned with these things for string matching, are they?

**Comment by aphillips** [comment]
The added text doesn't fully address this: it includes a "issue" box in the text. Need to discuss with the WG?

**Comment by aphillips** [comment]
This is now stale. The issue box is removed and the Note covers where string-search lives.
