### ISSUE TITLE
ref to 10646 in charmod

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#15]
[raised by Uma Umamaheswaran, https://lists.w3.org/Archives/Public/www-international/2015JulSep/0032.html]

http://www.w3.org/TR/2015/WD-charmod-norm-20150721/ has:

[ISO10646]
Information Technology - Universal Multiple- Octet Coded CharacterSet (UCS) - Part 1: Architecture and Basic Multilingual Plane. ISO/IEC10646-1:1993. The current specification also takes into consideration the first five amendments to ISO/IEC 10646-1:1993. Useful <a href="http://www.egt.ie/standards/iso10646/ucs-roadmap.html">roadmaps</a>show which scripts sit at which numeric ranges.

Should not this be updated to the latest published 10646 with changed title, and updated link to the roadmaps?

See http://standards.iso.org/ittf/PubliclyAvailableStandards/index.html.

ISO/IEC 10646:2014 (4th edition) Information technology -- Universal Coded Character Set (UCS)

Link to the roadmaps (from SC2 livelink standing document, pointing to unicode roadmaps): http://isotc.iso.org/livelink/livelink/fetch/-8919192/8919217/8919258/8919381/SD1_SC2_Roadmaps.html?nodeid=16854978&vernum=-2

**Comment by aphillips** [comment]
This isn't one of our locally created references. That means it's a flaw in respec's list of references. Need to follow up in their project.

**Comment by aphillips** [comment]
I'm getting varying results from ReSpec. Need to followup.

**Comment by aphillips** [comment]
Just checked this. ReSpec has this complaint about the `[ISO10646]` reference:

> Legacy SpecRef entries are not supported: [[ISO10646]]. Please update it at https://github.com/tobie/specref/

Looking at https://api.specref.org/bibrefs?refs=ISO10646 makes me unsure what to fix about the reference. More attention is needed here.

**Comment by aphillips** [comment]
I added ISO10646 to our local biblio. It's not perfect, but it fixed respec's yelling at me. Keeping this issue open in order to fix later.
