### ISSUE TITLE
Discouraging Legacy Character Encodings

### ISSUE THREAD

**Issue by stpeter** [w3c/charmod-norm#155]
This has likely been discussed before, but at https://w3c.github.io/charmod-norm/#legacyCharacterEncoding I'm wondering if it makes more sense for the first Note to instead be a best practice with conformance language, like so:

"Documents, formats, and protocols SHOULD use a Unicode character encoding, such as UTF-8, since no additional utility is be gained from using a legacy character encoding and the considerations in the rest of this section would be completely avoided."

**Comment by aphillips** [comment]
Excellent suggestion, although...

Documents is an advisory to authors and I have no problem with the recommendation.

Formats and protocols are guidance to spec authors. We should have several guidance for them:

- You must allow a Unicode encoding, preferably UTF-8
- you should make UTF-8 the default encoding
- you should not allow legacy encodings

Thoughts?

**Comment by aphillips** [comment]
Thinking a little further...

I am trying to keep all the Mustard (requirements) in section 3 onwards, with none in Sections 1 or 2 (the pedagogic materials). We do have some best practices in Section 3.1.1, although maybe not direct enough ones.

We might include a forward reference in Section 2.7 (#legacyCharacterEncoding) to the best practices and stronger language (I like your language a lot) against using non-Unicode encodings. Thoughts?

**Comment by stpeter** [comment]
+1 that sounds great.

**Comment by andjc** [comment]
I'd be inclined to go further and flag the problems inherent in pseudo -Unicode encodings, not just legacy encodings.

Most devs have no real idea about psuedo-Unicode encodings.

**Comment by r12a** [comment]
I wouldn't object to mustard creeping into earlier sections if it makes it easier for readers to grok the important information and reduces redirects.

**Comment by aphillips** [comment]
I agree. It's just that the text in this case is in a big green NOTE box and hard to miss. We could increase the visibility even further ("note well", etc.). I guess it's that I don't see the *need* to mustardize outside the lower sections yet. Could you look at the current ED and see if you agree that we've covered it?

**Comment by aphillips** [comment]
in 2018-02-15 teleconference agreed to add forward reference in 2.7 to 3.1.1. no additional mustard item
