### ISSUE TITLE
Add code points to example 11

### ISSUE THREAD

**Issue by aphillips** [w3c/charmod-norm#157]
copied from #154 

   https://w3c.github.io/charmod-norm/#canonical_compatibility

In Example 11, it might be helpful to include the Unicode code points.

**Comment by aphillips** [comment]
@stpeter have a look at the changed ED and let me know if this addresses your comment

**Comment by r12a** [comment]
[Not a request] In case you'd like to display code for q̣̇ in grouped fashion, note that v22 pickers such as https://r12a.github.io/pickers/latin/ will now produce the following for that sequence:

`<span class="codepoint" translate="no"><span lang="en">&#x0071;</span> + <span lang="en">&#x25CC;&#x0323;</span> + <span lang="en">&#x25CC;&#x0307;</span> [<span class="uname">U+0071 LATIN SMALL LETTER Q</span> + <span class="uname">U+0323 COMBINING DOT BELOW​</span> + <span class="uname">U+0307 COMBINING DOT ABOVE​</span>]</span>`

Looks like github produces that from code, so this is a more readable way to show what i'm getting at:
<span class="codepoint" translate="no"><span lang="en">&#x0071;</span> + <span lang="en">&#x25CC;&#x0323;</span> + <span lang="en">&#x25CC;&#x0307;</span> [<span class="uname">U+0071 LATIN SMALL LETTER Q</span> + <span class="uname">U+0323 COMBINING DOT BELOW​</span> + <span class="uname">U+0307 COMBINING DOT ABOVE​</span>]</span>

Just letting you know, in case.

**Comment by aphillips** [comment]
Closing since done. Reopen if necessary.
