### ISSUE TITLE
Arabic pair of combining marks on the same side appear same whatever their position.

### ISSUE THREAD

**Issue by ntounsi** [w3c/charmod-norm#162]
Section 2.2.1 > Example  of canonical equivalence > Order of combining marks > "q̣̇ vs.q̣̇" example :
At the beginning  "... the order of the combining marks might not represent a distinct character." seems to contradict "The order of combining diacritics on the same side have a positional meaning." at the end of the same pargarphe. (To my understanding of "positional meaning")

Anyway, this last sentence, "The order of combining diacritics on the same side have a positional meaning." might be true for the example "A base letter A followed by two combining marks (U+030A COMBINING RING ABOVE and U+0301 COMBINING ACUTE ACCENT)", i.e.  Ǻ vs. Á̊. But consider Arabic combining marks like Fatha (U+064E)  +  Shadda (U+0651). They both appear on the same side above a letter Beh (U+0628), say,  and Fatha is _always_ above the shadda  ![bfs](https://user-images.githubusercontent.com/15004708/38433938-8d9b2b28-39c4-11e8-86ff-6d6c5a4b12cc.jpeg) whatever the  order of combining marks :
Beh + Fatha + Shadda   
![b-f-s](https://user-images.githubusercontent.com/15004708/38434024-dff1839a-39c4-11e8-873f-1be040609bf8.jpeg)
or
Beh + Shadda + Fatha  
![b-s-f](https://user-images.githubusercontent.com/15004708/38434033-e929c800-39c4-11e8-9159-e69978c0ceb6.jpeg)

Is this what you mean by positional meaning?
Here we have two combining marks  on the same side of a letter, but without "positional meaning".

**Comment by aphillips** [comment]
@ntounsi Thanks for the comment. It probably should say "The order of combining diacritics on the same side often has a positional meaning" or something similar. The lack of positional meaning with fatha/shadda (and I'm sure there are lots other combinations in several scripts) doesn't remove the fact that the order does matter in other cases.

**Comment by aphillips** [comment]
Addressed in editors copy. Watch for merge.

**Comment by ntounsi** [comment]
Thanks @aphillips. You added "(although there are cases where the order doesn't matter to the presentation)"
In fact, in this case, the order of the combining marks doesn't matter to the meaning also.

**Comment by aphillips** [comment]
@ntounsi Thanks. In most cases where the presentation is the same the meaning is the same also. I wanted to stress the presentation since presumably identical presentation has identical meaning.
