### ISSUE TITLE
Canonically equivalent but may have different appearance.

### ISSUE THREAD

**Issue by ntounsi** [w3c/charmod-norm#163]
(May be  a font rendering problem, but worth to notice)

Same example as previous issue #162 , but with Kasra instead of Fatha. Kasra (U+0650) normally appears bellow Shadda (U+0651) and sometime bellow a letter. So regardless of the order  
![b-k-s](https://user-images.githubusercontent.com/15004708/38435158-c50a7cf4-39c8-11e8-8bd1-b2125e10898d.jpeg)  

or   

![b-s-k](https://user-images.githubusercontent.com/15004708/38435177-cc6f6e5a-39c8-11e8-8b97-2ebebfdfc8f5.jpeg)

you may have:

(A) 
![bks2](https://user-images.githubusercontent.com/15004708/38435247-075b71da-39c9-11e8-91f6-b91fc0bfa2b1.jpeg) (with Amiri font for example )

or

(B) 
![bks](https://user-images.githubusercontent.com/15004708/38435265-13c514d0-39c9-11e8-8fa3-bd000788ef28.jpeg) (with other fonts, more simple IMO)

But, for some (broken IMO) fonts, according to the order of combining marks, if Kasra is _before_ Shadda, the appearance _is_ like (A) above, and if Shadda is _before_ Kasra, it _is_ like (B).
However, the principle of canonical equivalence, at §2.2.1, second paragraph, states that "_**When correctly displayed**_ [ sequences of Unicode characters that represent the same abstract character] _should always have the same visual appearance and behavior_". 

The last example appears to contradict this principle... The appearance differs according to the sequence order of the pair of diacritics. Unless one notices what is, carefully, said "When correctly displayed". 
Does the example here, (A) for Beh+Kasra+Shadda and (B) for Beh+Shadda+Kasra, fit in the case of "correctly displayed" ?

**Comment by Richard57** [comment]
If it is a broken font, it is compliant with the Unicode standard.  The renderer would only be non-compliant if it deliberately rendered them differently.  However, I would say that sensitivity to the codepoint sequence means it is not correctly displayed for all canonically equivalent forms.

However, there is one major problem with this approach.  Following the example of the Unicode standards, compatibility ideographs are often rendered differently to their canonical equivalents, e.g. 金 U+F90A CJK COMPATIBILITY IDEOGRAPH-F90A v. 金 U+91D1 CJK UNIFIED IDEOGRAPH-91D1.  Rendering them the same would be inferior, as many pairs are distinguished in a national standard.  This is a problem with the Unicode model.  The modern resolution to this mess is to use variation sequences.

**Comment by aphillips** [comment]
@ntounsi That is, indeed, a very carefully worded bit of text--my hidden presumption is that the two strings being considered for equivalence are being rendered in the same rendering system and shown in the same font. The word "correct" here also includes things such as the proper positioning of combining marks and such. There are many variables that can cause two canonically equivalent but differently encoded strings to present differently. Perhaps it is good to say that. Check my new PR and see what you think.

**Comment by ntounsi** [comment]
More clear. My understanding is that the  case of (A) and (B) above, cononically equivalent but visually different, can be explained by  "factors that can cause them to appear somewhat differently".
