### ISSUE TITLE
Four forms of arabic letters but only two are rendered

### ISSUE THREAD

**Issue by ntounsi** [w3c/charmod-norm#164]
(Not significant issues, don't add anything to the essence of the example.)

Example 11 (Presentation forms of Arabic)

1) s / (initial, medial, final, isolated) / (isolated, final, initial, middle) /
to have the same order from top to bottom as the letters in the side example.

2) BTW, not all fonts render differences between letter position forms. 
Simple fonts generally use same form ![simple1](https://user-images.githubusercontent.com/15004708/38646851-96245320-3de1-11e8-9774-9263d3f14775.jpg) for initial ![fee7](https://user-images.githubusercontent.com/15004708/38646892-b5beff82-3de1-11e8-81e5-e52882ac08e8.jpg) and middle ![fee8](https://user-images.githubusercontent.com/15004708/38646913-c971319e-3de1-11e8-914e-4d586e361bfc.jpg), 
and same form ![simple2](https://user-images.githubusercontent.com/15004708/38646921-d2778324-3de1-11e8-8e07-4e98c4726c7a.jpg) for final ![fee6](https://user-images.githubusercontent.com/15004708/38646936-e0278bfe-3de1-11e8-9e60-9c8acb0230b3.jpg) and isolated ![fee5](https://user-images.githubusercontent.com/15004708/38646940-ea37ee4a-3de1-11e8-9cdc-63aecf4d1a40.jpg). 
(It's the case in my browser, with "times new roman", as in the document). 
May be use images or a font with the right shaping for each of the four forms. 
Note that "Courier New" would be OK.

**Comment by aphillips** [comment]
Good point. I agree that we should present the variant forms if we can. I'll need to adjust styles to accomplish this. Keeping open as needs work.

**Comment by r12a** [comment]
Fwiw, font is Times New Roman on my Mac (and doesn't show differences).  Noto Naskh Arabic makes the various forms distinct (many other fonts don't).

**Comment by aphillips** [comment]
I broke down and changed the example from NOON to HEH, since that letter has more distinct shapes--and both Richard and I use it in tutorials for that purpose. I also added text explaining what the presentation forms are currently useful for and illustrating that they are *not* used for encoding words in normal Arabic.

**Comment by ntounsi** [comment]
May be permute the order top-down in the list of Heh
U+FEEB, U+FEEC, U+FEEA, U+FEE9
 in stead of 
U+FEE9, U+FEEA, U+FEEB, U+FEEC
to march the order (initial, medial, final, isolated) in the text aside.
This would also suit to the example 12 of sequence of Heh.
