### ISSUE TITLE
Coneng Homonyms are Recent

### ISSUE THREAD

**Issue by Richard57** [w3c/charmod-norm#168]
According to Antelme in "Inventaire provisoire des caractères et divers signes des écritures khmères pré-modernes et modernes employés pour la notation du khmer, du siamois, des dialectes thaïs méridionaux, du sanskrit et du pāli", (aefek.free.fr/iso_album/antelme_bis.pdf) <U+17D2, U+178A KHMER LETTER DA> had a different form to <U+17D2, U+178F KHMER LETTER TA> as recently as the 1920's.

**Comment by aphillips** [comment]
This refers to Example 14 in [Section 2.3](http://w3c.github.io/charmod-norm/#normalizationLimitations), correct? 

That may be true, but example 14 is just three examples of possible homographs. The given sequences do appear identical on my computer ;-), even though they are logically distinct. Any any homographs may not be identical in all fonts or presentations. Do you disagree with showing the `COENG` examples?

**Comment by Richard57** [comment]
The wording implies that that the appearances are always at least similar.  The old form of <COENG, DA> was very distinct, even more so than the optional differences between U+0061 LATIN SMALL LETTER A and U+0251 LATIN SMALL LETTER ALPHA and between U+0067 LATIN SMALL LETTER G and U+0261 LATIN SMALL LETTER SCRIPT G.

The issue is that the degree of difference may differ wildly between *good* fonts, varying from deliberate identity of form to deliberate clear differences.

As to what you saw, you're probably using a font attuned to early 21st century Khmer.  The Arabic examples were clearly distinguishable on my machine, but it's just possible that that's due to different but genetically related fonts.

**Comment by aphillips** [comment]
@Richard57 Changed the text above the example to be more specific:

> Some character sequences that can sometimes appear very similar (or identical) in a single script include:

Does this address your concern?

**Comment by Richard57** [comment]
On Sat, 14 Jul 2018 13:21:05 -0700
Addison Phillips <notifications@github.com> wrote:

> @Richard57 Changed the text above the example to be more specific:
> 
> > Some character sequences that can sometimes appear very similar (or
> > identical) in a single script include:  
> 
> Does this address your concern?
> 

Yes.

**Comment by aphillips** [comment]
Thanks! (closing)
