### ISSUE TITLE
CGJ suppresses Line-Breaking

### ISSUE THREAD

**Issue by Richard57** [w3c/charmod-norm#169]
Section 2.5 says, "The character U+034F Combining Grapheme Joiner, whose name is misleading (as it does not join graphemes or affect line breaking)".  Strike out "or affect line breaking"; it confusingly continues to have property value "line_break = glue", just like U+00A0 NO-BREAK SPACE.  It would not be out of place gluing together some cuneiform characters that were at times a sequence of characters but at the text's time were single characters.

**Comment by aphillips** [comment]
Done.
