### ISSUE TITLE
Function of WJ

### ISSUE THREAD

**Issue by Richard57** [w3c/charmod-norm#170]
Section 2.5 says, "The Word Joiner is used to separate words in languages that do not use explicit spacing. An example would be the Thai language."

Where is the evidence that U+2060 is used to *separate* words?  TUS states that U+2060 WORD JOINER and U+FEFF ZWNBSP should only be used for line-breaking; this excludes any role in determining word boundaries.

The text was different in earlier versions.  For example, TUS 7.0 Section 23.2 says, 'U+2060 WORD JOINER behaves like U+00A0 NO-BREAK SPACE in that it indicates the absence of word boundaries; however _word joiner_ has no width'.  This encouraged WJ to be used to indicate the absence of a word boundary in Thai, but this capability was withdrawn in Unicode 8.0.0.  Implementers beware!

**Comment by aphillips** [comment]
@Richard57 You're correct. The text is just wrong here. ZWSP is the word separator. I went back and changed the text after re-reading the description in Ch23 of TUS v11.

**Comment by r12a** [comment]
This is just a suggestion, but i would have said that WJ's purpose is to prevent line-breaking between certain characters, and that it happens to be recommended as a replacement for FEFF, rather than the current text, which states that the other way round.

**Comment by aphillips** [comment]
@r12a Good point. I changed the paragraph to reflect that.
