### ISSUE TITLE
Bidi Example

### ISSUE THREAD

**Issue by Richard57** [w3c/charmod-norm#171]
The bidi paragraph in Section 2.5 overlooks a case that should be more familiar to European students of Hebrew - right to left text embedded in left to right text and being broken between lines.  For generalising the text, note that N'ko numbers are a decimal number system whose numbers are  written right-to-left.

**Comment by aphillips** [comment]
@Richard57 I don't see what you mean? The text in those two paragraphs just generally describe the bidi control characters. It doesn't say very much about presentation, as the focus here is that the controls are invisible characters whose presence or absence could affect string matching without the user being aware of it. Can you clarify what, if any, changes you think are needed in this specific context?

**Comment by Richard57** [comment]
The text implies that bidi issues only apply to text in right-to-left scripts.  English text may also include 'quotes' from a right-to-left script, and would therefore need to be subject to bidi processing.  The bidi is more commonly needed for right-to-left text because decimal numbers are stored in big-endian sequence, thereby readily creating a mix of directions and the occasional need for control characters.
I suggest that before 'This intermixing', you insert, 'Left-to-right scripts may similarly include quotes in right-to-left scripts'.

**Comment by asmusf** [comment]
The 'scripts' do not include quotes, but if you change your suggestion to "text in left-to-right scripts may....'  . . .

**Comment by aphillips** [comment]
@asmusf You're right, the text does imply that. I have tried to fix it.

@Richard57 I agree. I actually went further with a rewrite to ensure clarity. Here's the full quote:

> Finally, most scripts, when written horizontally, proceed from left-to-right. However, some scripts, such as Arabic and Hebrew, are written predominently from right-to-left. Texts can be written in a mix of these scripts or include character sequences, such as numbers or quotes in another script, that run in the opposite direction to other parts of the text. This intermixing of text direction is called bidirectional text or "bidi" for short. The Unicode Bidirectional Algorithm [UAX9] describes how such mixed-direction text is processed for display. For most text, the directional handling can be derived from the text itself. However, there are many cases in which the algorithm needs additional information in order to present text correctly. For more examples, see [html-bidi].

@Richard57 How do you want to be credited in the acknowledgements section btw? I currently have you as `@Richard57`.

**Comment by Richard57** [comment]
The new text addresses my concerns.

If I am to be credited, I should be credited as "Richard Wordingham".

**Comment by aphillips** [comment]
@Richard57 Thanks Richard, I updated your credit.

**Comment by aphillips** [comment]
I think this issue is ready to be closed. Please comment if needed.

**Comment by asmusf** [comment]
good to close
