### ISSUE TITLE
Webfont issues

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#188]
The CSS styling for .exampleChar currently says:
```
exampleChar {
    font-size: 36pt;
    font-family: "Palatino", "Times", "Times New Roman", "Verdana", "NoToFu", serif;
}
```
which for me yields:
![screen shot 2019-01-17 at 11 15 59](https://user-images.githubusercontent.com/4839211/51315328-d5001d00-1a49-11e9-92be-c4bce8232e98.png)

It should say:
```
exampleChar {
    font-size: 36pt;
    font-family: "NoToFu", "Palatino", "Times", "Times New Roman", "Verdana", serif;
}
```

which then gives a much more satisfactory results by actually illustrating the point you're trying to make, ie. that it's impossible to see the difference.
![screen shot 2019-01-17 at 11 15 40](https://user-images.githubusercontent.com/4839211/51315357-e77a5680-1a49-11e9-9823-c81a325f51bc.png)

**Comment by r12a** [comment]
Second problem is that the Khmer text isn't combining as needed.  It should look like this in Noto Sans Khmer. 

![screen shot 2019-01-17 at 11 23 33](https://user-images.githubusercontent.com/4839211/51315612-6f606080-1a4a-11e9-9e9d-cd90b7de8ded.png)

 I suspect you forgot to include the glyphs in your NoToFu webfont.

**Comment by aphillips** [comment]
This should mostly be addressed. The subset font itself isn't updated yet, but I moved NoToFu up in the fallback chain for examples and I added a WOFF font for Khmer to the stylesheet.
