### ISSUE TITLE
Arabic presentation forms not for showing composed forms

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#189]
Just above https://w3c.github.io/charmod-norm/#bidiCompatibilityExample
> Today these compatibility forms mainly are used to show the composed form in isolation on the page (to illustrate the shapes of the character without joining to another character in a word).

I've been giving charmod-norm one last read and suddenly noticed this for the first time. I don't think we should appear to be suggesting a use for these presentation characters for composed forms in isolation. If you need to show composed forms in isolation, ZWJ exists for that, and is likely to produce better results for at least two reasons: (a) because you can't rely on all fallback fonts to support presentation forms, (b) because the text you use is still machine readable and searchable.

I'd suggest either just dropping the sentence, or replacing it with something like "These presentation forms are intended to only support round-trip encoding conversions."

I'll drop a couple more comments in issues, but they should all be small editorial nits, don't worry.

**Comment by aphillips** [comment]
Fair enough. Addressed with a slightly more pedantic version of your suggestion:

> These presentation forms are intended only for the support of round-trip encoding conversions with the legacy character encodings that include equivalent presentation forms.
