### ISSUE TITLE
Not necessary to limit to East Asian characters

### ISSUE THREAD

**Issue by tkanai** [w3c/charmod-norm#19]
I'm afraid that the descriptions about "narrow vs. wide" in Fig.1 might just help spreading misunderstanding.

Compatibility equivalence affects not only to East Asian characters, but also to any sets of full and half width characters. For instance, Full-width Lattin Capital Letter A (U+FF21) is equivalent to 'A' in ASCII area.

As the word "East Asian Width" is not defined in this document, I think replacing the word to "width variants" which is used in UAX#15 would be more desirable. (and removing "of East Asian characters (often associated with legacy multibyte encodings)," as well.)

**Comment by aphillips** [comment]
I agree in general with this comment.

I think that East Asian character variation provides the most obvious examples, but they are only that: examples. Will modify in next edit round.

**Comment by aphillips** [comment]
Thanks again for this comment.

Please see commit  bbfaf03 and reopen if you think additional changes are needed.
