### ISSUE TITLE
[editional?] no need cite tag for reference

### ISSUE THREAD

**Issue by himorin** [w3c/charmod-norm#197]
in [line 423](https://github.com/w3c/charmod-norm/blob/a69231242ab20605d3d22618430b7a700ddd54f9/index.html#L423), we have cite tag as
``` html
in the Internationalization Working Group's document <cite>[[!INTERNATIONAL-SPECS]]</cite>, which
```
but it seems for me that we don't need this for respec.

**Comment by aphillips** [comment]
I don't understand. The cite tag is autogenerated by Respec. We intend this to be a reference. What am I missing?

**Comment by himorin** [comment]
Sorry I forgot to wrap reference line in pre (fixed the description), also not so clear.
Respec will convert cite tag in source html as `[[xxxx]]` into `[<cite yyy>xxx</cite>]`, so I assumed we don't need to have `<cite>` in our html in gh-pages.

Let me push something as PR.
