### ISSUE TITLE
possible typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/charmod-norm#202]
Thank you for the useful specification.
I found possible typos in Character Model for the World Wide Web: String Matching document.

Sec 1.1, NOTE: "nd" might be "and".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#issue-container-generatedID-1

Sec 2.2, EXAMPLE 10: "U+01FA LATIN LETTER CAPITAL" might be "U+01FA LATIN CAPITAL LETTER".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#aringExample

Sec 2.2.1, EXAMPLE 11: "U+017E" might be "U+0064 + U+017E".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#example-11

Sec 2.6, paragraph 7: "maintaing" might be "maintaining".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#x2-6-invisible-unicode-characters

Sec 2.7, paragraph 6: "U+FF0E" might be "U+FE0E" and "FF0F" might be "FE0F".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#x2-7-emoji-sequences

Sec 2.8, paragraph 3: as for "? [U+20AC EURO SIGN])", ")" should be deleted or "(" should be added before "[".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#x2-8-legacy-character-encodings

Sec 3.1.3, paragraph 7: "preponderence" might be "preponderance".
  https://www.w3.org/TR/2019/NOTE-charmod-norm-20190204/#x3-1-3-converting-to-a-sequence-of-unicode-code-points

**Comment by r12a** [comment]
Thanks for pointing these out.  It may take a while to get back to this work, but we'll make the corrections as soon as practicable.

**Comment by shujikamitsuna** [comment]
Thank you!

**Comment by aphillips** [comment]
@shujikamitsuna Thank you again for these. I have examined the above. They are all errors.

**Comment by shujikamitsuna** [comment]
@aphillips, Thank you too!
