### ISSUE TITLE
add section for other kinds of equivalence

### ISSUE THREAD

**Issue by aphillips** [w3c/charmod-norm#23]
Outside of Unicode normalization and case folding, there exist certain types of "interesting equivalence" that may be useful, particularly in searching text. For example, Japanese uses two syllabic scripts, `hiragana` and `katakana`. A user searching a document may type in one script, but wish to find equivalent text in the other script. This equivalence exists outside of Unicode, but can affects features like text find. Acknowledging these kinds of variations and documenting them for users could be useful?

**Comment by duerst** [comment]
Please "but can affects" to "but can affect".

**Comment by aphillips** [comment]
I can't find "but can affects" in the current ED

**Comment by duerst** [comment]
It's in the text at the start of this issue. I thought that text would go into the document more-or-less as is. If not, then we should be fine.
