### ISSUE TITLE
Definition of "transcoder"

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#55]
The definition of "transcoder" in the 2016-02-01 Editor's Draft (not obviously present in the TR version), contains the note phrase "... converts code units (generally bytes)...".   There are a number of historical two-byte CCSs whose code units are certainly not bytes.  If one were inclined to quibble, the code units for ASCII / ISO 646 are seven-bit objects and not bytes either.    Transcoders from stateful seven or eight bit systems, based on ISO 2022 or otherwise, may be converting bytes, but not only bytes.

Recommendation: drop the parenthetical note: it seems to be confusing, wrong for a lot of cases, and to not add anything helpful.   Alternately, if there was some point intended by including it, that point should be made more clearly and explained.

**Comment by aphillips** [comment]
My point in including the parenthetical "(generally bytes)" is that "code units" is a term of art that I didn't want to pause to explain. People familiar with encodings will instantly grok what I mean. But those who are not may need some guide post. The use of the word "generally" was meant to indicate exactly what you outline--the bytes (and here I mean octets, really) are not always the code unit in question, even if that's true for the most familiar encodings.

I can drop the parenthetical, if you think it detracts from our purpose. Or I can explain code units. Thoughts?

**Comment by klensin** [comment]
--On Wednesday, February 03, 2016 19:00 -0800 aphillips
notifications@github.com wrote:

> My point in including the parenthetical "(generally bytes)" is
> that "code units" is a term of art that I didn't want to pause
> to explain. People familiar with encodings will instantly grok
> what I mean. But those who are not may need some guide post.
> The use of the word "generally" was meant to indicate exactly
> what you outline--the bytes (and here I mean octets, really)
> are not always the code unit in question, even if that's true
> for the most familiar encodings.
> 
> I can drop the parenthetical, if you think it detracts from
> our purpose. Or I can explain code units. Thoughts?

I think there is a superficial explanation of "code unit" that
defines in in terms of the intrinsic number of bits associated
with a code point in the CCS that might serve the purpose better
than either a complete explanation of "code unit" or "generally
bytes".  Given the above, I understand why you did that, but the
problem is the large number of people who are not "familiar with
encodings" (to the point necessary for instantaneous grokking)
but who still have a clue or think they do.  For that
intermediate range, which might include a very large fraction of
the intended audience for the spec, "generally bytes" could be
very confusing.

**Comment by aphillips** [comment]
Trying again, this time for avoidance--it's orthogonal to this document, really.

> A transcoder is a process that converts text between two character encodings. 
> Most commonly in this document it refers to a process that converts from a 
> legacy character encoding to a Unicode encoding form, such as UTF-8.

**Comment by klensin** [comment]
In this (and several other issues), I am trying to argue more strongly for avoiding unnecessary controversy that could detract from the document than for any particular change or position, so the above works fine for me.

**Comment by aphillips** [comment]
Cool. Thanks.
