### ISSUE TITLE
Definition of "Syntactic content" (section 1.4)

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#56]
The text reads, in part, " For example, '<' or '>' are part of the syntactic content in an HTML document."  

First, that should probably either be "'<' and '>' are..." or  "'<' or '>' is...", I think the first.  Second and more important, while one can figure it out after reading the subsequent text, I believe that statement would be a lot more clear if it read:
" For example, '<' and '>' and the element name they typically surround are part of the syntactic content in an HTML document."  
(Drop "typically" if appropriate -- I can't think of exceptions.)
(Also note that, while '<' is (AFAICT) always syntactic content, '>' may sometimes just be part of the text.)

**Comment by aphillips** [comment]
Done. New text:

> ```
>       For example, <span class="qchar">&lt;</span> and <span class="qchar">&gt;</span>
>      (as well as the element name and various attributes they surround) 
>     are part of the syntactic content in an HTML document. </p>
> ```

**Comment by aphillips** [comment]
Closing. Reopen if unsatisfied.
