### ISSUE TITLE
XML use of DTD (Section 1.4, Example 1 in 2016-02-01 Editor's version)

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#57]
Text reads "...also allows a user to define elements and attributes for a given document using a DTD".   Having been victimized by the great DTD versus Schema divide, it might be useful to either say "...using, for example, a DTD" here or to mention both alternatives.

**Comment by aphillips** [comment]
Done.

**Comment by aphillips** [comment]
Closing. Reopen if unsatisfied.
