### ISSUE TITLE
Definition of "natural language content' (Section 1.4)

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#58]
The text reads "and not to any of the surrounding syntactic content or identifiers that form part of the document structure..."  

Clarity would be improved by saying "... any of the surrounding or embedded syntactic content..."
Also, given the way syntactic content is defined, aren't identifiers that form part of the document structure also syntactic content?  Is so, "or identifiers" is either redundant, confusing, or both.

Text also reads " Note that the natural language content can include items such as the document title as well..."   That would be less likely to confuse if it said "... can include items such as document or section titles as well..."

**Comment by aphillips** [comment]
Good points. I rewrote the paragraph slightly and I added a different example at the end. I also reversed the comparison (not "the natural language contain can include" but rather "the syntactic content can include natural language"

Here's the revised para:

> ```
>    <p><dfn>Natural language content</dfn> refers to the language-bearing
>     content in a document and <b>not</b> to any of the surrounding or embedded 
>      syntactic content that form part of the document structure. You can think
>      of it as the actual "content" of the document or the "message" in a
>      given protocol. Note that syntactic content can contain natural
>      language content, such as when an [[HTML]] <code class="kw">img</code> element
>      has an <code class="kw">alt</code> attribute containing a description of
>      the image.</p>
> ```

**Comment by aphillips** [comment]
Closing. Reopen if unsatisfied.
