### ISSUE TITLE
Provide descriptions of Unicode case folding

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#6]
http://www.w3.org/TR/2015/WD-charmod-norm-20150721/#unicode-case-insensitive

Need to insert descriptions of common, full, and simple unicode case-folding. Richard mentions: The above needs significant expansion - it's some of the stuff that we need to explain most clearly to spec developers and implementers. We should also add that the case folding algorithms are somewhat different from the simple upper and lower case conversions.

**Comment by annevk** [comment]
Where do we actually want to use this in the platform? Is it used anywhere currently?

**Comment by aphillips** [comment]
http://www.w3.org/TR/css-fonts-3/#font-family-casing

... is an example. Actually, it is helpful to read the section holistically. We start by recommending case sensitivity. For ASCII-only namespaces, ASCII case fold matching a la HTML is suggested and you'd be most familiar with this in the platform. Most new namespaces permit Unicode identifiers. Spec authors need to be aware that, Unicode being what it is, case insensitivity is not a trivial operation. By documenting this in Charmod, we hope to avoid recreating the material each time this arises---in practice most spec authors come to their senses and use case sensitive matching as a result. When they can't (or won't be dissuaded), the documentation is ready as well.

**Comment by r12a** [comment]
my initial intent in clarifying what it involves is also to make spec developers think twice about requiring it for syntax-relevant comparisons. The charmod-norm doc aims to educate developers as well as making recommendations.  These types of case-folding certainly crop up in discussion (quite often), and it would be useful to summarise what the terms mean, and the implications of using that approach. 

On the other hand, there may be a case for unicode case folding in searching algorithms that look for text in the natural language content provided by user input or author-developed content. (tbc)

**Comment by aphillips** [comment]
Exactly so.

**Comment by aphillips** [comment]
Closing as addressed in above commit.
