### ISSUE TITLE
Section number references to Unicode Standard

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#61]
References to particular sections, by number, in The Unicode Standard should probably not link to that standard using  http://www.unicode.org/versions/latest/.   Section numbers change between versions and do not track.  For example, the last sentence in the definition and discussion of "grapheme" (Section 1.2 of the 2016-02-01 Editor's Draft (not obviously present in the TR version) reads

" (A discussion of grapheme clusters is also given at the end of Section 2.10 of the Unicode Standard, [Unicode].)"

However, in Unicode 7.0 (aka "latest" at the time of this writing), Section 2.10 is about writing direction and does not appear to mention graphemes or grapheme clusters at all.

**Comment by aphillips** [comment]
A good point. I refried the Section 2.10 reference to be generically to Chapter 2, adding a link to the specific version 8.0 section 2.11. The other reference, still correct, was to section 5.18, but I made an identical adjustment to avoid future numbering woes.

**Comment by aphillips** [comment]
Closing. Reopen if unsatisfied.
