### ISSUE TITLE
Terminology example(s) (Section 1.4.1 of 2016-02-01 Editor's version, former Example 3)

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#62]
To preserve the parallel structure (and because it is confusing otherwise), "User values" should be defined in Section 1.4.

**Comment by aphillips** [comment]
A fair point. I added a definition, but note that "user value" or "user values" only currently appears in the section on terminology. It probably should appear elsewhere, since it is a consideration in the requirements on matching, for example.
