### ISSUE TITLE
Section 2 introduction

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#64]
The text reads:
"These formats or protocols can be viewed as a set of text files (resources) that include..."
However, the definition of "resource" goes to some lengths to indicate that the term is not a synonym for "text file", so the parenthetical note is, at best, confusing.  Is what is intended closer to:

"These formats or protocols can be viewed as a set of resources (e.g., text files) that include..."

**Comment by aphillips** [comment]
Well... but the point is that they *_are *_ text files. Yes, some "resources" are MP3 files or JPEGs, but the structure of the Web and Web protocols consists of text, where markup is not binary gibberish. I included the word "resources" parenthetically to remind people that we will be using that term later. If it is confusing, I can just remove it.

**Comment by klensin** [comment]
This is where the meaning of "resource" (see #59) becomes important.  As part of the URN discussions, it became clear that the RFC 3986 definition of "resource" could include pet rocks, abstractions with no physical representation, and even a stray wildebeest or pony or herd thereof.  So, perhaps sadly, they are not limited to text files.  Certainly the particular types of resources described are text files, but simply putting "resources" in parens after "set of text files" implies that they are synonyms, which they are not.  Recommend either dropping "(resources)" or expanding it to say "a type of resource" or the like.

**Comment by aphillips** [comment]
Would this work better:

> These formats or protocols can be viewed as a set of resources consisting mainly of text files that include some form of structural markup or syntactic content.

**Comment by aphillips** [comment]
@klensin Is the current draft enough to close this issue?

**Comment by aphillips** [comment]
Closing this issue. Reopen if needed.
