### ISSUE TITLE
String matching problem (Section 2 introduction) -- types of operations

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#65]
The text reads
"...string-based operations such as matching, indexing, searching, sorting, regular expression matching, and so forth."
If "regular expression matching" is really intended to mean "regular expression processing", say that.  Otherwise, this would be more clear if, instead of seeming to include matching generally and then turning around and specifying some particular type as if it were an exception, the text read something like
" string-based operations such as matching (including regularly expression matching), indexing, searching, sorting, and so forth."

This paragraph also does not provide a good lead-in to what follows.  A sentence to the effect that most of those operations can be affected by user perceptions of how different strings relate and transformations that may be applied to more nearly match those perceptions.

**Comment by aphillips** [comment]
Done.

@klensin I think I addressed your comments in the above commit. Please have a look.

**Comment by aphillips** [comment]
Closing. Reopen if unsatisfied.
