### ISSUE TITLE
Case Folding introduction (Section 2.1)

### ISSUE THREAD

**Issue by klensin** [w3c/charmod-norm#67]
It may not be relevant (or even, by other measures, correct), but I've been beaten up several times by scholars of Arabic calligraphy who have claimed by any treatment of the distinction among initial, medial, final, and isolated forms as different from the distinction between upper, lower (and maybe title) case reflects a European script bias and not actual relationships.

In the last sentence of the first paragraph, "as well as scripts such as Greek, Armenian, or Cyrillic." should be "as well as scripts such as Greek, Armenian, and Cyrillic." 

Further in this section, s/storage when performaing/storage when performing/

**Comment by asmusf** [comment]
I respectfully disagree with those scholars, and beating up people is not to be encouraged.

For one, in terms of digital text representation, the various positional forms for Arabic (or Mongolian) characters are simply different glyphs; they are selected by the layout engine, and not encoded separately as characters. (Leaving aside the compatibility characters for Arabic that correspond to an earlier attempt and exist as an aid for emulators and other types of code museums).

While there is a similarity, that in each case, around the concept of a "letter" there is a set of shapes that this letter can take on, "casing" represents of a subset: a bi-cameral script, as the name says, has two sets of forms for each letter, and the choice of form is not one of typography but of orthography, with conventions when to use each one that are based on the content of the text and the intent of the author.

In contrast, the positional forms for cursively connected (and similar) scripts are determined solely (or primarily) by the nature of the adjacent letters.

Also, the description in section 2.1 conforms to the definition of casing found elsewhere, e.g. in the Unicode Standard, and there's little to be gained to suddenly pretend that the term encompasses scripts that are not bi-cameral (but nevertheless have multiple shapes for the same letters).

Finally, case folding requires that there be multiple code points for the same letter and that ignoring that distinction is a common process (Hiragana and Katakana are an example of two sets of shapes for the same sound values, which are not customarily folded, even though all users know which two form the set for the given sound).

**Comment by aphillips** [comment]
I have to agree with @asmusf here. Further, case folding, particularly of ASCII, is a well-known text normalization that software developers (and W3C Spec authors) can get wrong unless they are aware of it. It requires addressing head-on.

Regarding this comment:

> In the last sentence of the first paragraph, "as well as scripts such as Greek, Armenian, or Cyrillic." 
> should be "as well as scripts such as Greek, Armenian, and Cyrillic." 

Um... I don't see the difference? What did you intend?

**Comment by duerst** [comment]
This is what I originally posted (in e-mail):

> > > > I fully agree with John. I don't have any experience of being beaten
> > > > up by experts on that point, but then only because I never even got
> > > > the idea to make such a point.

I'm sorry for the delay in coming back to this issue, but I somehow misread John Klensin's comment, and got everything mixed up. As a result, I have to disagree with John, and agree with Asmus and Addison Phillips. The initial/medial/final/isolate distinction in Arabic is of quite a different nature than the casing distinctions in Latin/Greek/Cyrillic/... In addition to what has already been said, I'd like to mention that the Arabic calligraphy experts that I have been in interaction with, in particular Tom Milo, always insisted that the four-way distinction was a hopelessly crude approximation to what good typography and calligraphy for Arabic warranted.

**Comment by asmusf** [comment]
On 2/11/2016 11:22 PM, Martin Dürst wrote:

> This is what I originally posted (in e-mail):
> 
> ```
>             I fully agree with John. I don't have any experience
>             of being beaten
>             up by experts on that point, but then only because I
>             never even got
>             the idea to make such a point.
> ```
> 
> I'm sorry for the delay in coming back to this issue, but I somehow 
> misread John Klensin's comment, and got everything mixed up. As a 
> result, I have to disagree with John, and agree with Asmus and Addison 
> Phillips. The initial/medial/final/isolate distinction in Arabic is of 
> quite a different nature than the casing distinctions in 
> Latin/Greek/Cyrillic/... In addition to what has already been said, 
> I'd like to mention that the Arabic calligraphy experts that I have 
> been in interaction with, in particular Tom Milo, always insisted that 
> the four-way distinction was a hopelessly crude approximation to what 
> good typography and calligraphy for Arabic warranted.

I remember the same lecture from Tom.

A./

**Comment by aphillips** [comment]
(laughing) I just had several days of that lecture from Tom in Oman.

That said, while I have to agree with the sentiment (but then: who claims that plain text Latin represents "good typography" either, eh?), I do have to point out that initial/medial/final/isolate is a  _useful _ rough approximation for talking about that script.

@klensin Carefully reading your comment, I have fixed _or Cyrillic_ to _and Cyrillic_. I also fixed the spelling error (thank you for pointing it out).

@klensin Also in careful re-reading, whether I agree or disagree with those scholars, I suspect that this is out-of-scope for our document. We're describing text comparison as it exists in the Unicode encoding model. Case variation is a distinct part of the encoding model and is inherent in every programming language I can think of. Arabic presentation forms are actually covered by Unicode Normalization. We might wish to add an example of the same.

In addition, though, this brings to mind a different issue with the section on string searching (presence or absence of Arabic short vowels). I will open a separate issue for that item.

Having addressed the editorial issues, I will close this item. Please reopen if not satisfied.
