### ISSUE TITLE
conformance criteria numbering being reset

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#7]
http://www.w3.org/TR/2015/WD-charmod-norm-20150721/

the numbering of the conformance criteria, Cxx, restarts with each level three section. The numbering should be unique throughout the document.

**Comment by aphillips** [comment]
Hmm... this was working. Note that eventually we will need to "fix" the numbers and make them permanent.

**Comment by aphillips** [comment]
Fixed in cd2012b
