### ISSUE TITLE
table widths

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#81]
after i replaced the experimental version of respec with the current standard, several tables spanned the full width of the screen.  We'll need to fix that.

**Comment by aphillips** [comment]
I see the problem. I'm following @fantasai's guidance in the stylesheet to use table.data (`<table class="data">`) for these, though. Is the problem the stylesheet?

**Comment by r12a** [comment]
after looking into it, i think the problem is that you use 

`<div class="overlarge">`

around the table. Remove that and things look a log better.

**Comment by r12a** [comment]
looks like this is fixed, no?
