### ISSUE TITLE
❿ hasn't a compat equiv

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#83]
http://w3c.github.io/charmod-norm/#dfn-compatibility-equivalence

the table lists ❿ as a circled compat equiv character, but i don't believe it is.

http://r12a.github.io/uniview/?char=277F

**Comment by r12a** [comment]
also the collection ｶ     カ     ︷     { implies that these are all compat characters, and doesn't explain that one of each is the normalised form.

**Comment by r12a** [comment]
and finally, 🄠 is more akin to ⑴ in the last row than it is to the <square> characters it is alongside.

**Comment by duerst** [comment]
Confirmed that ❿ isn't a compatibility character. All the (white) circled numbers are, but the black ones aren't, because they can't be made simply by taking the numbers and encircling them.

**Comment by aphillips** [comment]
U+277F is incorrect

The collection of East Asian width and rotated forms are taken directly from the table in UAX15.

U+1F120 appears to be a typo.

**Comment by aphillips** [comment]
These changes have already been implemented, so marking for closure.
