### ISSUE TITLE
Case matching example seems wrong

### ISSUE THREAD

**Issue by r12a** [w3c/charmod-norm#99]
http://w3c.github.io/charmod-norm/#definitionCaseFolding

> For example, this occurs when matching class names between an HTML document and its associated style sheet. Consider this HTML fragment:
> Example 3
> 
> <style type="text/css">
> 
>   SPAN.h\e9llo {
>      text-decoration: underline;
>   }
> </style>
> 
> 
> <span class="h&#xe9;llo">Hello World!</span>
> 
> The SPAN in the stylesheet matches the span element in the document, even though one is uppercase and the other is not.

The text before the example box talks about matching class names, but the example shows matching of element names.  (Note that the escaped é is rather distracting, and i'm not sure why it's there. It _is_ in the class name, but there's no case distinction.)

**Comment by aphillips** [comment]
You're right. I will fix the text to refer to elements.

Note that the escaped é is there because we use the exact same example elsewhere in the document.
